# Generated by Django 3.2.4 on 2021-06-29 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='researchdata/letters')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_url_embed', models.URLField(blank=True, null=True)),
                ('location_other', models.CharField(blank=True, max_length=255, null=True)),
                ('knowledge_of_judeospanish', models.CharField(blank=True, choices=[('NTV', 'I learned Judeo-Spanish as a native/home language in childhood'), ('LTR', 'I learned Judeo-Spanish as a non-native language later in life'), ('NVR', "I don't know Judeo-Spanish")], max_length=3, null=True)),
                ('author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('admin_published', models.BooleanField(default=False)),
                ('meta_created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('meta_lastupdated_datetime', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('data_use_agreements', models.ManyToManyField(blank=True, related_name='story', to='researchdata.DataUse')),
                ('languages', models.ManyToManyField(blank=True, related_name='story', to='researchdata.Language')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.location')),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location_birth_other', models.CharField(blank=True, max_length=255, null=True)),
                ('location_current_other', models.CharField(blank=True, max_length=255, null=True)),
                ('knowledge_of_judeospanish', models.CharField(blank=True, choices=[('NTV', 'I learned Judeo-Spanish as a native/home language in childhood'), ('LTR', 'I learned Judeo-Spanish as a non-native language later in life'), ('NVR', "I don't know Judeo-Spanish")], max_length=3, null=True)),
                ('name_of_judeospanish', models.CharField(blank=True, max_length=255, null=True, verbose_name='By what name(s) do you call Judeo-Spanish?')),
                ('comments', models.TextField()),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('meta_created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('meta_lastupdated_datetime', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('languages', models.ManyToManyField(blank=True, related_name='participant', to='researchdata.Language')),
                ('location_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_birth', to='researchdata.location', verbose_name='Location of Birth')),
                ('location_current', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_current', to='researchdata.location', verbose_name='Current Location')),
                ('participation_activities', models.ManyToManyField(blank=True, related_name='participant', to='researchdata.ParticipationActivity')),
            ],
        ),
    ]
