# Generated by Django 3.2.4 on 2021-06-02 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='researchdata/letters')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('location_other', models.CharField(blank=True, max_length=255, null=True)),
                ('knowledge_of_judeospanish', models.CharField(blank=True, choices=[('NTV', 'I learned Judeo-Spanish as a native/home language in childhood'), ('LTR', 'I learned Judeo-Spanish as a non-native language later in life'), ('NVR', "I've never learnt Judeo-Spanish")], max_length=3, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('admin_published', models.BooleanField(default=True)),
                ('meta_lastupdated_datetime', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meta_firstpublished_datetime', models.DateTimeField(blank=True, null=True, verbose_name='First Published')),
                ('languages', models.ManyToManyField(blank=True, related_name='story', to='researchdata.Language')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.location')),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
    ]
