# Generated by Django 3.2.6 on 2021-08-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0002_data_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_player_embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
